services:
  mosquitto:
    image: eclipse-mosquitto:2
    ports:
      - "1883:1883"
    volumes:
      - ./mosquitto.conf:/mosquitto/config/mosquitto.conf
    restart: unless-stopped

  zigbee2mqtt:
    image: koenkk/zigbee2mqtt:latest
    depends_on:
      - mosquitto
    volumes:
      - ./zigbee2mqtt:/app/data
      - /run/udev:/run/udev:ro
    devices:
      - /dev/ttyUSB0:/dev/ttyUSB0
    environment:
      - TZ=Europe/Berlin
    restart: unless-stopped

  bridge:
    image: ghcr.io/n0xum/zigbee-controller:latest
    restart: unless-stopped
    depends_on:
      - mosquitto
    network_mode: host
    volumes:
      - ./config.yaml:/app/config.yaml:ro
      - ./hap-data:/app/hap-data
